version: '2'
services:
  znc-master:
    image: znc-git:latest
    ports:
      - "1025:1025"
    volumes:
      - "./znc-master:/home/znc/.znc"
    environment:
      - "LOCAL_USER_ID=${LOCAL_USER_ID}"
  znc-work:
    image: znc-git:latest
    ports:
      - "9345:1025"
    volumes:
      - "./znc-work:/home/znc/.znc"
    environment:
      - "LOCAL_USER_ID=${LOCAL_USER_ID}"
