version: '3.2'
services:
  znc-master:
    image: znc-git:latest
    ports:
      - "1025:1025"
    volumes:
      - "./znc-master:/home/znc/.znc"
  znc-laptop:
    image: znc-git:latest
    ports:
      - "9345:1025"
    volumes:
      - "./znc-slave:/home/znc/.znc"
